---
#
# Ansible managed
#
repository:
  description: Download, extract and write bootable USB image.
  homepage: https://robertdebock.nl/
  topics: biosupdate, lenovo, security, ansible, molecule, tox, playbook
