---
language: python

python:
  - "3.7"

services:
  - docker

env:
  matrix:
    - image="docker-debian-systemd" tag="stable"
    - image="docker-debian-systemd" tag="unstable"
    - image="docker-debian-systemd"
    - image="docker-fedora-systemd"
    - image="docker-fedora-systemd" tag="rawhide"
    - image="docker-ubuntu-systemd" tag="rolling"
    - image="docker-ubuntu-systemd" tag="devel"
    - image="docker-ubuntu-systemd"

matrix:
  allow_failures:
    - env: image="docker-debian-systemd" tag="unstable"
    - env: image="docker-fedora-systemd" tag="rawhide"
    - env: image="docker-ubuntu-systemd" tag="rolling"
    - env: image="docker-ubuntu-systemd" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "QvTfMPRmyuuXoKu1NQlRXDcCGEuboEwOC9hL1KwhOeb8FsxFsWZIF1QCBqs8JJuKSpzdM2maI0yx9sus/hcnxG0LKe5HdpeTnTgjd50+Z+DfiQpiAA4pZSRQlB8qxjTcdkgbB8xeTn/k01X1bOppuzwtM2XfZ9fdviUYKpIApZtbCKgoZePFVQNiDoU0EnA5EUlKqcgqiRRbRcDzmouGSvMq0z74fFXtbeY76vkodeDCWaB7ps3YM74b/smZ48Uggx56IvQTeb4Ys4FOnXeqMzFre3QiqnU9y1fHgBOnxTJ8YXikJpuEJcdwvnHA9iS1Qa0XBParkDWCClSxq7fjoe1KYvW6XyI2rzi75/kaS44KkTe3z3h0PtJCE7boZTknUDG556EKoXWgMnxvLzst4tHYHJTHM8UJC78vPsNOwZ2PbId3KuL1UwMhDY3pki1sdzrUu68nt0uGyTalBWjkIJnUB9JN4Jsby40r+gF2tkxpdGfeboDTcj4BYZs8sawVMTqsQ9EEIoAePMAHaXg2MwFz7h2QsjewaFAi/yoRrxTEdkWqZnRt7HzDxgIhDDkNThjLVEeVPZ2rXNKGi1p1gwuUtTKud2e6soZyIA2riRuy+oLDj8pXJlzNWaFfcH8GyxiTeQqI6kvjzC7p0527obIjBATzaWmVWoGBSo8kwD0="
  email: false
