---

- name: test if bios_update_temporary_directory is set correctly
  assert:
    that:
      - bios_update_temporary_directory is defined
    quiet: yes

- name: test if bios_update_url is set correctly
  assert:
    that:
      - bios_update_url is defined
    quiet: yes

- name: test if bios_update_flash_drive is set correctly
  assert:
    that:
      - bios_update_flash_drive is defined
    quiet: yes
