---
# tasks file for bios_update

- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: install requirements
  package:
    name: "{{ bios_update_requirements }}"
    state: present

- name: download bios update bootable cd
  block:
    - name: get bios_update
      get_url:
        url: "{{ bios_update_url }}"
        dest: "{{ bios_update_temporary_directory }}/{{ bios_update_url | basename }}"
        validate_certs: no
  rescue:
    - name: show problem
      debug:
        msg:
          - "The model '{{ ansible_product_version }}' is unknown."
          - "Please set bios_update_url to proceed."
          - "Error: {{ bios_update_download_bios_update_bootable_cd }}"
    - name: stop play
      meta: end_play

- name: extract bootable image
  command: "{{ bios_update_full_command }}"
  args:
    creates: "{{ bios_update_temporary_directory }}/bios_update.img"

- name: write bootable image to flash drive
  command: dd if={{ bios_update_temporary_directory }}/bios_update.img of={{ bios_update_flash_drive }} bs=64K
  args:
    creates: "{{ bios_update_flash_drive }}1"
  when:
    - not bios_update_ci_mode
